config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'chatroom#index'

	# manage the sessions
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	#manage the message
	post 'message', to: 'messages#create'

	mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	scope :custom_display, -> { order(:created_at).last(20) }

	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages

	validates :username, presence: true
	validates :username, length: { in: 3..15 }
	validates :username, uniqueness: true
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		#returns the id of the current user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		#will chec if we have a logged in user
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:error] = 'You must be logged in to perform that action'
			redirect_to login_path
		end
	end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	before_action :require_user, only: %i[index]
	def index
		@messages = Message.custom_display
		@message = Message.new
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			ActionCable.server.broadcast 'chatroom_channel',
			                             { message: message_render(@message) }
		end
	end

	private

	def message_params
		params.require(:message).permit(:body)
	end

	def message_render(message)
		render(partial: 'shared/message', locals: { message: message })
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :logged_in_redirect, only: %i[new create]
	def new
		logged_in_redirect
	end

	def create
		user = User.find_by(username: params[:session][:username].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = 'You have successfully logged in'
			redirect_to root_path
		else
			flash.now[:error] =
				'There was something wrong with your login information'
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = 'You have successfully logged out'
		redirect_to login_path
	end

	private

	def sessions_params
		params.require(:session).permit(:username, :password)
	end

	def logged_in_redirect
		if logged_in?
			flash[:error] = 'You are already logged in'
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<div class="text-center py-3">
    <i class="fas fa-coffee root-icon fa-2x p-3 rounded-circle border-width-3 text-warning"></i>
  <h4>Say something</h4>
</div>

<div class="container mb-md-3">
  <div class="row justify-content-between">

    <div class="col-12 col-md-8  shadow rounded-lg">
      <div class="chatbox pt-1 d-flex flex-column">

        <div class="content mb-auto" id="messages-container">
          <% @messages.each do |message| %>
            <%= render 'shared/message', message: message%>
          <% end %>
        </div>

        <%= form_for(@message, url: message_path, remote: true, html:{class:"border-top pt-2 d-flex pb-2 pb-md-0", role: 'form'}) do |f|%>

          <%= f.text_field :body, class:"form-control", placeholder: "Enter a message..." %>

          <%= f.button '<i class="fas fa-paper-plane"></i>'.html_safe ,class:"btn btn-warning" %>

        <% end %>


      </div>
    </div>



    <div class="d-none d-md-block col-md-3 shadow rounded-lg">
      <div class="chatbox">
        <nav class="nav flex-column nav-fill bg-dark rounded-lg my-3 ">
          <a class="nav-link nav-btn text-white border-bottom border-light text-left" href="#">Home</a>
          <a class="nav-link nav-btn text-white border-bottom border-light text-left" href="#">Messages</a>
          <a class="nav-link nav-btn text-white text-left" href="#">Friends</a>
        </nav>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
      <%= render 'shared/menu' %>
      <%= render 'shared/error_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% flash.each do |message_type, message_content| %>

<div class="alert alert-<%= message_type == "error" ? 'warning' : message_type %> alert-dismissible fade show" role="alert">
  <%= message_content %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<% end %>

app/views/shared/_menu.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Chatroom", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Messages</a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? %>
          <%= link_to "Log out", logout_path, class:"dropdown-item", method: :delete %>
        <% else %>
          <%= link_to "Log in", login_path, class:"dropdown-item" %>
        <% end %>
          <a class="dropdown-item" href="#">Sign up</a>
        </div>
        </li>
        <% if !logged_in? %>
          <li class="nav-item">
            <a class="btn px-3 btn-primary rounded-lg" href="#">Log in</a>
          </li>
        <% end %>
    </ul>
  </div>
</header>

app/views/shared/_message.html.erb
<div class="event">
  <p class="mb-1"> <em><a href="#"> <%= message.user.username %></a> </em>: <%= message.body %></p>
</div>